AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Cloud Resume Challenge - Visitor Counter Infrastructure'

Resources:
  VisitorCounterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  VisitorCounterFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${AWS::StackName}-VisitorCounter-${AWS::Region}'
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorCounterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCounterTable
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: !GetAtt VisitorCounterTable.Arn
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VisitorCounterApi
            Path: /visitorCount
            Method: GET

  VisitorCounterTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${AWS::StackName}-VisitorCounter-${AWS::Region}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST


Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for the visitor counter function"
    Value: !Sub "https://${VisitorCounterApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitorCount"