name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'template.yml'
      - 'lambda/**'
      - 'HTML/**'
  workflow_dispatch:  # This allows manual triggering

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r lambda/requirements.txt

    - name: Run tests
      run: |
        cd lambda
        pytest tests/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # or your preferred region

    - name: SAM build
      run: sam build

    - name: SAM deploy
      run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

    # Updated step for HTML deployment
    - name: Deploy HTML to S3
      run: |
        aws s3 sync ./HTML s3://witcoskitech.com --delete

    - name: Invalidate CloudFront Distribution
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"